[package]
name = "dioxus-bevy-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18", features = ["dynamic_linking"] }
dioxus = { version = "0.7", default-features = false, features = [
    "macro",
    "signals",
    "hooks",
] }
dioxus-rsx = { version = "0.7", optional = true }

[features]
hot_reload = ["dioxus-rsx"]
debug = []

[[example]]
name = "demo"

[profile.dev]
opt-level = 1
debug = true
