[package]
name = "dioxus-bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18", default-features = false, features = ["ui", "dynamic_linking", "debug"] }
dioxus = { version = "0.7", default-features = false, features = [
    "macro",
    "signals",
    "hooks",
] }
dioxus-rsx = { version = "0.7", optional = true }

[features]
hot_reload = ["dioxus-rsx"]

[[example]]
name = "demo"

[profile.dev]
opt-level = 1
